### ISSUE TITLE
State always starts as moored

### ISSUE THREAD

**Issue by bergie** [meri-imperiumi/signalk-autostate#9] opened 2020-01-31 18:30 UTC
If the system starts whilst we're moving, it still goes to `moored` for the first 10 minutes before enough movement has been detected. We could utilize `speedOverGround` to prevent this. Or maybe not set state between `sailing`/`moored` until we have 10 minutes of data.

**Comment by marcobergman** [comment] 2023-06-19 18:09
Hi, could you have a look at this issue with a view to resolving it? I restart signalk regularly while en route, and this issue causes many false logbook entries. Thx!

**Comment by bergie** [comment] 2023-06-20 05:23
Maybe the best option would be to persist the state on disk every time it changes, and read it on start-up.

**Comment by marcobergman** [comment] 2023-06-20 06:58
Good thinking. There is something else wrong here in my simulated environment, though, which I haven't figured out yet. It might be caused by myself. I'm trying to get the debug statements in StateMachine.js working but I get no output anywhere? How would I see these outputs? Thx!

**Comment by marcobergman** [comment] 2023-06-20 10:02
I have set the interval to 1 minute and 10m. He sometimes skips to 'moored', and that happens after an interval of 2 minutes, while I have set the interval to 1 minute:

```
Jun 20 11:14:59 Has moved > 10m (185 meters in 1 minutes, 3.08m/s)
Jun 20 11:14:59 Set state position to 52°20′11″N 1°6′39″W

Jun 20 11:15:59 Has moved > 10m (184 meters in 1 minutes, 3.07m/s)
Jun 20 11:15:59 Set state position to 52°20′10″N 1°6′48″W

Jun 20 11:17:59 Has only moved 0 meters in 0 minutes (0.00m/s)
Jun 20 11:17:59 State has changed from sailing to moored
Jun 20 11:17:59 Set state position to 52°20′8″N 1°7′8″W

Jun 20 11:18:59 Has moved > 10m (184 meters in 1 minutes, 3.07m/s)
Jun 20 11:18:59 State has changed from moored to sailing
Jun 20 11:18:59 Set state position to 52°20′7″N 1°7′18″W

Jun 20 11:20:59 Has only moved 0 meters in 0 minutes (0.00m/s)
Jun 20 11:20:59 State has changed from sailing to moored
Jun 20 11:20:59 Set state position to 52°20′5″N 1°7′37″W

Jun 20 11:21:59 Has moved > 10m (184 meters in 1 minutes, 3.07m/s)
Jun 20 11:21:59 State has changed from moored to sailing
Jun 20 11:21:59 Set state position to 52°20′4″N 1°7′47″W

Jun 20 11:22:59 Has moved > 10m (184 meters in 1 minutes, 3.07m/s)
Jun 20 11:22:59 Set state position to 52°20′3″N 1°7′56″W

Jun 20 11:23:59 Has moved > 10m (187 meters in 1 minutes, 3.12m/s)
Jun 20 11:23:59 Set state position to 52°20′1″N 1°8′6″W
```

**Comment by marcobergman** [comment] 2023-06-20 11:18
Possible; the litmus test for me is in the logging of signalk-logbook, but I cannot judge how this affects other applications of this plugin's output, navigation.status.

**Closed** 2023-07-23 12:17 UTC
Labels: bug
